//! Honor rustc's path-remapping contract in embedded compiler diagnostics.
//!
//! Rustc remaps file paths it emits, but cannot remap arbitrary string
//! literals generated by a proc macro from its process arguments. Those
//! include output directories and extern/native library paths. Normalize
//! this diagnostic copy only; actual compiler arguments are never changed.

const OPTION: &str = "--remap-path-prefix";

pub(crate) fn normalize(flags: &[String]) -> Vec<String> {
	let remaps: Vec<_> = flags
		.iter()
		.enumerate()
		.filter_map(|(index, flag)| {
			flag.strip_prefix("--remap-path-prefix=")
				.or_else(|| {
					(flag == OPTION)
						.then(|| flags.get(index.saturating_add(1)))
						.flatten()
						.map(String::as_str)
				})
				.and_then(|value| value.rsplit_once('='))
				.filter(|(source, _)| !source.is_empty())
		})
		.collect();

	flags
		.iter()
		.enumerate()
		.map(|(index, flag)| {
			let mapping = flag
				.strip_prefix("--remap-path-prefix=")
				.or_else(|| {
					index
						.checked_sub(1)
						.and_then(|previous| flags.get(previous))
						.filter(|previous| *previous == OPTION)
						.map(|_| flag.as_str())
				});
			if let Some((_, destination)) = mapping.and_then(|value| value.rsplit_once('=')) {
				let prefix = if flag.starts_with("--remap-path-prefix=") {
					"--remap-path-prefix="
				} else {
					""
				};
				return format!("{prefix}<remapped>={destination}");
			}

			remap_argument(flag, &remaps)
		})
		.collect()
}

fn remap_argument(argument: &str, remaps: &[(&str, &str)]) -> String {
	let mut output = String::with_capacity(argument.len());
	let mut rest = argument;
	let mut boundary = true;
	while !rest.is_empty() {
		// Rustc uses the last matching mapping, not the longest prefix.
		let mapping = boundary
			.then(|| {
				remaps
					.iter()
					.rev()
					.find(|(source, _)| rest.starts_with(source))
			})
			.flatten();
		if let Some((source, destination)) = mapping {
			output.push_str(destination);
			rest = rest.strip_prefix(source).unwrap_or(rest);
			boundary = false;
			continue;
		}

		let mut characters = rest.chars();
		let Some(character) = characters.next() else {
			break;
		};
		output.push(character);
		rest = characters.as_str();
		boundary =
			character == '=' || character == ',' || character == '"' || character.is_whitespace();
	}
	output
}

#[cfg(test)]
mod tests {
	use super::normalize;

	fn flags(target: &str) -> Vec<String> {
		[
			"/toolchain/bin/rustc".to_owned(),
			"--cfg".to_owned(),
			"feature=\"d1\"".to_owned(),
			"--out-dir".to_owned(),
			format!("{target}/release/deps"),
			"--extern".to_owned(),
			format!("dependency={target}/release/deps/libdependency.rlib"),
			format!("-Lnative={target}/release/build/native/out"),
			format!("--remap-path-prefix={target}=/target"),
			"--remap-path-prefix=/toolchain=/rustc".to_owned(),
		]
		.into()
	}

	#[test]
	fn separate_build_directories_embed_the_same_compiler_diagnostics() {
		let a = normalize(&flags("/tmp/repro/a"));
		let b = normalize(&flags("/tmp/repro/b"));
		assert_eq!(a, b);
		assert_eq!(a[0], "/rustc/bin/rustc");
		assert_eq!(&a[1..3], ["--cfg", "feature=\"d1\""]);
		assert_eq!(a[4], "/target/release/deps");
		assert_eq!(a[6], "dependency=/target/release/deps/libdependency.rlib");
		assert_eq!(a[7], "-Lnative=/target/release/build/native/out");
		assert!(!a.iter().any(|flag| flag.contains("/tmp/repro/")));
	}

	#[test]
	fn mappings_apply_once_and_last_match_wins() {
		let flags = [
			"/root/sub/file.rs",
			"--remap-path-prefix=/root/sub=/specific",
			"--remap-path-prefix=/root=/broad",
			"--remap-path-prefix=/broad=/again",
		];
		let normalized = normalize(&flags.map(str::to_owned));
		assert_eq!(normalized[0], "/broad/sub/file.rs");
	}

	#[test]
	fn rustc_textual_prefix_matching_preserves_unmapped_flags() {
		let flags = [
			"--extern=crate=/build-other/lib.rlib",
			"--cfg",
			"feature=\"d1\"",
			"-Copt-level=3",
			"--remap-path-prefix=/build=/source",
		];
		let normalized = normalize(&flags.map(str::to_owned));
		assert_eq!(normalized[0], "--extern=crate=/source-other/lib.rlib");
		assert_eq!(&normalized[1..4], &flags[1..4]);
		let unchanged = ["--cfg", "feature=\"d1\"", "/root/file.rs"];
		assert_eq!(normalize(&unchanged.map(str::to_owned)), unchanged);
	}

	#[test]
	fn separate_mapping_arguments_and_non_ascii_paths_are_supported() {
		let flags =
			["--extern=crate=/build/niño/lib.rlib", "--remap-path-prefix", "/build=/source"];
		let normalized = normalize(&flags.map(str::to_owned));
		assert_eq!(normalized, [
			"--extern=crate=/source/niño/lib.rlib",
			"--remap-path-prefix",
			"<remapped>=/source"
		]);
	}
}
